src/Application/Controllers/CaptchaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Application.Controllers
{
    /// <summary>
    /// 验证码
    /// </summary>
    public class CaptchaController : Controller
    {
        /// <summary>
        /// 服务器端滑块验证方法
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public bool Post([FromBody] List<int> datas)
        {
            var sum = datas.Sum();
            var avg = sum * 1.0 / datas.Count;
            var stddev = datas.Select(v => Math.Pow(v - avg, 2)).Sum() / datas.Count;
            return stddev != 0;
        }
    }
}

src/Application/Controllers/LoginController.cs
using Application.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Application.Controllers
{
    public class LoginController : Controller
    {

        public string ErrorMessage { get; set; }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Validate(IFormCollection formCollection)
        {
            string username = formCollection["username"];
            string password = formCollection["password"];
            bool remember = string.IsNullOrEmpty(formCollection["remember"]);

            return RedirectToAction("Index");
        }
    }
}

src/Application/Views/Login/Index.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!--load jquery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!--load font-awesome -->
    <script defer src="~/font-awesome/js/all.min.js"></script>
    <!--load slidercaptcha -->
    <link href="~/css/slidercaptcha.min.css" rel="stylesheet" />
    <!-- Bootstrap core CSS -->
    <link href="~/css/sign-in/signin.css" rel="stylesheet" />

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @@media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .slidercaptcha {
            display: none;
            margin: 0 auto;
            width: 300px;
            height: 286px;
            border-radius: 4px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.125);
            margin-top: 40px;
            z-index: 1080;
            position: absolute;
        }

            .slidercaptcha .card-body {
                padding: 1rem;
            }

            .slidercaptcha canvas:first-child {
                border-radius: 4px;
                border: 1px solid #e6e8eb;
            }

            .slidercaptcha.card .card-header {
                background-image: none;
                background-color: rgba(0, 0, 0, 0.03);
            }

        .refreshIcon {
            top: -54px;
        }
    </style>
</head>
<body class="text-center">

    <main class="form-signin">
        <form id="form" action="@Url.Action("Validate","Login")" method="post" >

            <img class="mb-4" src="~/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
            <div class="form-row">
                <div class="col-12">
                    <div class="slidercaptcha card">
                        <div class="card-header">
                            <span>请完成安全验证!</span>
                        </div>
                        <div class="card-body">
                            <div id="captcha"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-floating">
                <input name="username" type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
                <input name="password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>
            <div class="checkbox mb-3">
                <label>@ViewBag.ErrorMessage</label>
                <label>
                    <input name="remember" type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="button" id="login">Sign in</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>

        </form>
    </main>

    <script src="~/js/longbow.slidercaptcha.min.js"></script>
    <script>
        sliderCaptcha({
            id: 'captcha',
            width: 270,
            height: 150,
            sliderL: 42,
            sliderR: 9,
            offset: 5,
            loadingText: '正在加载中...',
            failedText: '再试一次',
            barText: '向右滑动填充拼图',
            repeatIcon: 'fa fa-redo',
            setSrc: function () {

            },
            remoteUrl: "@Url.Action("Post", "Captcha")",
            verify: function (arr, url) {
                var ret = false;
                $.ajax({
                    url: url,
                    data: JSON.stringify(arr),
                    async: false,
                    cache: false,
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    success: function (result) {
                        ret = result;
                    }
                });
                return ret;
            },
            onSuccess: function () {
                $(".slidercaptcha").css("display", "none");
                $("#form").submit();
            },
            onFail: function () {

            },
            onRefresh: function () {
            }
        });
    </script>

    <script>
        $(function () {
            $("#login").click(function () {
                $(".slidercaptcha").css("display", "block");
            });
        });
    </script>
</body>
</html>